server {
    listen 80;
    server_name _;
    root /var/www/html/public;

    # Serve Laravel application
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP handling (Laravel)
    location ~ \.php$ {
        fastcgi_pass backend_fpm:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
